### ISSUE TITLE
Hookable version missmatch

### ISSUE THREAD

**Issue by suits-at** [nuxt/bridge#1078]
### Environment

- Operating System: Windows_NT
- Node Version:     v18.18.2
- Nuxt Version:     2.17.3
- CLI Version:      3.10.0
- Nitro Version:    2.8.1
- Package Manager:  pnpm@8.12.1
- Builder:          vite
- User Config:      bridge, modules, hooks, styleResources, optimizedImages, buildModules, srcDir, loading, env, vue, head, css, render, build, plugins, router, vite, serverHandlers, devServerHandlers, devServer, typescript, nitro

### Reproduction

https://stackblitz.com/edit/github-wuyjgw?file=package.json

### Describe the bug

Nuxt 2.17.3 uses hookable v4, stable bridge (3.0.0.) uses hookable v5. If you try to run `pnpm i && pnpm run dev` you will get a SyntaxError saying `The requested module 'PATH/hookable.js' does not provide an export named 'createHooks'.` With NPM it does work by the way, so seems to be related to how PNPM handles different versions of the same package. Downgrading nuxt to 2.17.2 also solves the issue, as there is no hookable v4 in use then.

**Comment by AlexandrKlepikov** [comment]
Same here. Reported also here https://github.com/nuxt/bridge/issues/506#issuecomment-1900717868

**Comment by iamVitalya** [comment]
Hi all! Guys, did you manage to solve it?
Rolling back from 2.17.3 to 2.17.2 did not help - I still have the same error.

<img width="582" alt="image" src="https://github.com/nuxt/bridge/assets/53257037/3ec198be-e829-4389-b7cb-87b8fc202092">
<img width="595" alt="image" src="https://github.com/nuxt/bridge/assets/53257037/10c79ed9-d9fe-45b0-a332-2dc44ed66cd0">

**Comment by wattanx** [comment]
It might be possible to work around this in the following ways:
(This is a temporary fix until the root of the problem is resolved.)

1. `pnpm add -D hookable@5.5.3`
    - hookable v5 does not support IE, but nuxt bridge does not support IE either. 
2. add `public-hoist-pattern[]=*hookable*` in `.npmrc`

**Comment by wattanx** [comment]
Resolved at https://github.com/nuxt/bridge/pull/1086
It will be released in `3.1.0`.
(If you want to try it quickly, you can try `@nuxt/bridge-edge@3.0.1-28436495.f604cdf`.)

**Comment by kaliloulah1155** [comment]
Hello guy how you resolve it please

**Comment by wommy** [comment]
there seems to be a hookable version mismatch between nuxt 2.18.1 and nuxt/bridge 3.3.1
with the bridge code grabbing the nuxt version hookable

`npm i -D hookable` fixed my error,
i also had to add `npm i -D defu`

**Comment by SliverYuki** [comment]
> Resolved at [#1086](https://github.com/nuxt/bridge/pull/1086) It will be released in `3.1.0`. (If you want to try it now, you can try `@nuxt/bridge-edge@3.0.1-28436495.f604cdf`.)
> 
> https://stackblitz.com/edit/github-wuyjgw-vr4sfq

This issue has not really been resolved, and it still occurs when using npm or yarn.

My environment:
Operating System: Mac OS
Node Version: v18.20.5
Nuxt Version: 2.18.1
Bridge Version: 3.4.0
CLI Version: 3.12.0
Package Manager: 10.8.2
Builder: webpack

**Comment by rottifant** [comment]
> > Resolved at [#1086](https://github.com/nuxt/bridge/pull/1086) It will be released in `3.1.0`. (If you want to try it now, you can try `@nuxt/bridge-edge@3.0.1-28436495.f604cdf`.)
> > https://stackblitz.com/edit/github-wuyjgw-vr4sfq
> 
> This issue has not really been resolved, and it still occurs when using npm or yarn.
> 
> My environment: Operating System: Mac OS Node Version: v18.20.5 Nuxt Version: 2.18.1 Bridge Version: 3.4.0 CLI Version: 3.12.0 Package Manager: 10.8.2 Builder: webpack

Experienced the same problem as @SliverYuki.


> `npm i -D hookable` fixed my error,
> i also had to add `npm i -D defu`

This "fixed" it for me, but imo this should be fixed directly in Bridge.
